name: update-version
on:
  push:
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-18.04
    services:
      repository:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: update
        run: |
          git log -n 1 $(git branch --show-current) --oneline | cut -d " " -f 1 > version.txt
          git add version.txt
          git commit -m ":memo: update API version"