name: update-version
on:
  push:
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: update
        uses: actions/checkout@v2
        run: |
          git log -n 1 $(git branch --show-current) --oneline | cut -d " " -f 1 > version.txt
          git add version.txt
          git commit -m ":memo: update API version"