name: update-version
on:
  push:
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: change and commit
        run: |
          git config --local user.email "test@test"
          git config --local user.name "Github-action [bot]"
          git log -n 1 master --oneline | cut -d " " -f 1 > version.txt
          git add version.txt
          git commit -m ":memo: update API version"
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}