name: update-version
on:
  push:
    branches:
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: commit and push
        run: |
          git config --local user.email " "
          git config --local user.name " "
          git log -n 1 $(git branch --show-current) --oneline | cut -d " " -f 1 > version.txt
          git add version.txt
          git commit -m ":memo: update API version"
          git push origin master